- name: redhat | Installing EPEL Repo (RedHat)
  yum:
    name: "epel-release"
    state: "present"
  become: true
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora"

- name: redhat | installing pip
  package:
    name:
      - python-pip
    state: present
  become: true
  when: >
        ansible_os_family == "RedHat" and
        ansible_distribution != "Fedora"